FROM nvcr.io/nvidia/pytorch:21.02-py3

ARG DEBIAN_FRONTEND="noninteractive"
RUN apt update && apt upgrade -y \
    &&  apt install -y default-libmysqlclient-dev \
    &&  apt clean \
    &&  rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

WORKDIR /work